package.json
=> fix: change package name

Doppler.AccountPlans/Startup.cs
=> [NO-TICKET] - Add CORS

Doppler.AccountPlans.Test/GetPlanInformationTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Model/PlanInformation.cs
add enpoint to get selected plan information
=> Dat 582 add enpoint to get selected plan information

Doppler.AccountPlans.Test/AuthorizationTest.cs, Doppler.AccountPlans.Test/GetCalculateUpgradeCostTestTest.cs, Doppler.AccountPlans.Test/GetPlanDiscountInformationTest.cs, Doppler.AccountPlans.Test/GetPlanInformationTest.cs, Doppler.AccountPlans.Test/MonthlyHandlerTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Enums/RenewalPeriodEnum.cs, Doppler.AccountPlans/Factory/IRenewalFactory.cs, Doppler.AccountPlans/Factory/RenewalFactory.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Model/DiscountPrepayment.cs, Doppler.AccountPlans/Model/PlanAmountDetails.cs, Doppler.AccountPlans/Model/PlanDiscountInformation.cs, Doppler.AccountPlans/Model/PlanInformation.cs, Doppler.AccountPlans/RenewalHandlers/AnnualHandler.cs, Doppler.AccountPlans/RenewalHandlers/BiannualHandler.cs, Doppler.AccountPlans/RenewalHandlers/MonthlyHandler.cs, Doppler.AccountPlans/RenewalHandlers/QuarterlyHandler.cs, Doppler.AccountPlans/RenewalHandlers/RenewalHandler.cs, Doppler.AccountPlans/Startup.cs, Doppler.AccountPlans/Utils/DateTimeProvider.cs, Doppler.AccountPlans/Utils/IDateTimeProvider.cs
We add Handlers to calculate, apportionment adjustments, discount prepayment and total for a Summary section in checkout process.
Can you review it?
=> feat: [DAT-589] Add Calculate Upgrade Cost endpoint

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
change month total calculation
=> fix: change month total calculation

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Fix issue in the calculate endpoint
=> fix(calculate): Fix issue in the calculate endpoint

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Fix issue in the calculate amount when the client is monthly.
Task: [DAT-666](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-666)
=> [DAT-666] - Fix issue in the calculate amount when the client is monthly

Dockerfile, Doppler.AccountPlans.Test/Doppler.AccountPlans.Test.csproj, Doppler.AccountPlans/Doppler.AccountPlans.csproj, package.json, yarn.lock
Update Dependabot dependencies
=> chore: Update dependabot

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans.Test/GetCalculateUpgradeCostTestTest.cs, Doppler.AccountPlans.Test/GetPlanInformationTest.cs, Doppler.AccountPlans/Enums/UserTypesEnum.cs, Doppler.AccountPlans/Model/PlanInformation.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
We fix a problem for Prepaid accounts, with this fix always return 0 in the mount to favor
=> fix: [DAT-683] Fix calculate for prepaid plans

Doppler.AccountPlans.Test/AuthorizationTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs
We split the SQL consults for Calculate upgrade endpoint because the repository has many responsibilities
=> feat: [DAT-697] Refactor calculate upgrade endpoint

Doppler.AccountPlans.Test/GetPlanDiscountInformationTest.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Model/PlanDiscountInformation.cs
Include the 'ApplyPromo' property in the response of the discounts endpoint.
**Response:**
```
[
{
"idDiscountPlan": "1",
"discountPlanFee": 0,
"monthPlan": 1,
"applyPromo": true
},
{
"idDiscountPlan": "2",
"discountPlanFee": 5,
"monthPlan": 3,
"applyPromo": false
},
{
"idDiscountPlan": "4",
"discountPlanFee": 15,
"monthPlan": 6,
"applyPromo": false
},
{
"idDiscountPlan": "6",
"discountPlanFee": 25,
"monthPlan": 12,
"applyPromo": false
}
] 
```
**Task:** [DAT-701](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-701)
=> feat(discounts): Include the 'ApplyPromo' in the discounts endpoint

Dockerfile, Doppler.AccountPlans.Test/Doppler.AccountPlans.Test.csproj, Doppler.AccountPlans/Dockerfile, Doppler.AccountPlans/Doppler.AccountPlans.csproj
Update solution to use net6
Task: [DAT-827](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62/backlog?selectedIssue=DAT-827)
=> [DAT-827] - Update solution to use net6

Doppler.AccountPlans.Test/GetPromoCodeTest.cs, Doppler.AccountPlans/Model/Promotion.cs
Add Duration property in the Promotion entity
**Task:** [DAT-893](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-893)
=> [DAT-893] - Add Duration property in the Promotion entity

Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
Fix issue when the client has a canceled plan
=> [No-Ticket] - Fix issue when the client has a canceled plan

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans.Test/GetPlanInformationTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IPromotionRepository.cs, Doppler.AccountPlans/Infrastructure/PromotionRepository.cs, Doppler.AccountPlans/Model/DiscountPlanFeeAdmin.cs, Doppler.AccountPlans/Model/PlanAmountDetails.cs, Doppler.AccountPlans/Model/UserPlanInformation.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Calculate the details of the total when the user can to upgrade the monthly plans.
Task: [DAT-997](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-997)
=> [DAT-997] - Integrate upgrade between plans

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IPromotionRepository.cs, Doppler.AccountPlans/Infrastructure/PromotionRepository.cs, Doppler.AccountPlans/Model/TimesApplyedPromocode.cs, Doppler.AccountPlans/Model/UserPlanInformation.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Change logic to calculate the duration of the promocode and current total
**Task:** [DAT-1017](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1017)
=> [DAT-1017] - Change logic to calculate the duration of the promocode and current total

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Fix issue when calculate the next invoice amount
=> [No-Ticket] - Fix issue when calculate the next invoice amount

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Model/DiscountPrepayment.cs, Doppler.AccountPlans/Model/UserPlanInformation.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Integrate update between contacts plans
**Task:** [DAT-984](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-984)
=> [DAT-984] - integrate update between contacts plans

Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Model/DiscountPromocode.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Integrate the new checkout with buy credits.
**Task:** [DAT-1066](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1066)
=> [DAT-1066] - Integrate the new checkout with buy credits

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Fix issue to calculate the discount admin.
**Task:** No ticket
=> [No-Ticket] - fix issue to calculate the discount admin

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Fix issue when calculate the total and the plan is no montly
=> [No-ticket] -Fix issue when calculate the total and the plan is no montly

Doppler.AccountPlans/Model/DiscountPlanFeeAdmin.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Issue when calculate the current amount invoice
=> [no-ticket] - Issue when calculate the current amount invoice

Dockerfile, Doppler.AccountPlans.Test/Doppler.AccountPlans.Test.csproj, Doppler.AccountPlans/Dockerfile, Doppler.AccountPlans/Doppler.AccountPlans.csproj
=> [DAT-1376] - update to .net 7

Dockerfile, Doppler.AccountPlans.Test/Doppler.AccountPlans.Test.csproj, Doppler.AccountPlans/Dockerfile, Doppler.AccountPlans/Doppler.AccountPlans.csproj
=> [DAT-1376] - Update dependencies

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Model/PlanAmountDetails.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Include amout of the unsed credits and also the positive balance
=> [DAT-1411] - Include amout of the unsed credits and also the positive balance

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Issue when calculate positive balance
Task: [DAT-1427](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1427)
[DAT-1427]: https://makingsense.atlassian.net/browse/DAT-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1427] - Issue when calculate positive balance

Doppler.AccountPlans/Controllers/AccountPlansController.cs
Return a maximum of the amount of the last purchase without extra credits.
**Task:** [DAT-1432](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1432)
[DAT-1432]: https://makingsense.atlassian.net/browse/DAT-1432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1432] - Return a maximum of the amount of the last purchase without extra credits

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Fix issue when calculate the positive balance when day is minor that 21
=> [No-Task] Wrong calculate the positive balance when day is minor that 21

Doppler.AccountPlans/Controllers/AccountPlansController.cs
Fix issue when calculate the price by credit
=> [No-ticket] - Fix issue when calculate the price by credit

Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromChatPlanHelper.cs, Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromMarketingPlanHelper.cs, Doppler.AccountPlans/Model/PlanAmountDetails.cs
Calcula la fecha de la próxima factura
**Task:** [DAT-1850](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1850)
[DAT-1850]: https://makingsense.atlassian.net/browse/DAT-1850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1850] -  Calculate date for the next invoice

Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Model/BasePlanInformation.cs, Doppler.AccountPlans/Model/ConversationPlanInformation.cs
Create an endpoint to return the details of plan
Task: [DAT-1852](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1852)
[DAT-1852]: https://makingsense.atlassian.net/browse/DAT-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1852] - Create an endpoint to return the details of plan

Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs
Add endpoint to get conversation plans
**Task:** [DAT-1884](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1884)
[DAT-1884]: https://makingsense.atlassian.net/browse/DAT-1884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1884] - Add endpoint to get conversation plans

Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/PromotionRepository.cs
**Task:** [DAT-1897](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1897)
[DAT-1897]: https://makingsense.atlassian.net/browse/DAT-1897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1897] Include nolock in the sql query

Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/PromotionRepository.cs, Doppler.AccountPlans/Startup.cs, Doppler.AccountPlans/TimeCollector/ITimeCollector.cs, Doppler.AccountPlans/TimeCollector/TimeCollector.cs, Doppler.AccountPlans/TimeCollector/TimeCollectorItem.cs, Doppler.AccountPlans/TimeCollector/TimeCollectorLogWritter.cs, Doppler.AccountPlans/TimeCollector/TimeCollectorLogWritterSettings.cs, Doppler.AccountPlans/TimeCollector/TimeCollectorScope.cs, Doppler.AccountPlans/TimeCollector/TimeCollectorServiceCollectionExtensions.cs
Task: [DAT-1933](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1933)
[DAT-1933]: https://makingsense.atlassian.net/browse/DAT-1933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1933] Add time collector

Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Enums/PlanTypeEnum.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Model/LandingPlanInformation.cs
Task: [DAT-1926](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1926)
[DAT-1926]: https://makingsense.atlassian.net/browse/DAT-1926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1926] Add GET Landing Plans endpoint

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans.Test/GetCalculateUpgradeLandingPlanCostTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Model/LandingPlanSummary.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Task: [DAT-1930](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1930)
[DAT-1930]: https://makingsense.atlassian.net/browse/DAT-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DAT-1930 - Calculate landing plan fee

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Task: [DAT-1981](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1981)
[DAT-1981]: https://makingsense.atlassian.net/browse/DAT-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1981] Calculation of the total monthly landing plan

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Enums/BillingCreditTypeEnum.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Task: [DAT-1952](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1952)
[DAT-1952]: https://makingsense.atlassian.net/browse/DAT-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1952] Discount already paid landing plans

Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Update logic to calculate the positive balance.
**Task:** [DAT-1983](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1983)
[DAT-1983]: https://makingsense.atlassian.net/browse/DAT-1983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-1983] - Update logic to calculate the positive balance

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
fix issue to calculate the discount of the payment already paid
=> fix issue to calculate the discount of the payment already paid

Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Fix issue when calculate the total and next invoice date
=> Fix issue when calculate the total and next invoice date

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Fix issue to calculate total for the landing plan
=> [No-Task] Fix issue to calculate total for the landing plan

Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromMarketingPlanHelper.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
fix issue when calculate the next invoice
=> [No-Ticket] fix issue when calculate the next invoice

Doppler.AccountPlans/Enums/BillingCreditTypeEnum.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
Fix issue to calculate the amount
=> [No-Ticket] Fix issue to calculate the amount

Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromChatPlanHelper.cs
Update calculate amount endpoint to support chat plan.
**Task:** [DAT-2068](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2068)
[DAT-2068]: https://makingsense.atlassian.net/browse/DAT-2068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2068] - Update calculate amount endpoint

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
fix issue to calculate amount landing
=> [No-Task] fix issue to calculate amount landing

Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Model/ConversationPlanInformation.cs
Include additional amounts
**Task:** [DAT-2086](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2086)
[DAT-2086]: https://makingsense.atlassian.net/browse/DAT-2086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-208] Include additional amounts

Doppler.AccountPlans/Controllers/AccountPlansController.cs
Create new endpoint get plan information given planId and type
**Task:** [DAT-2093](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2093)
[DAT-2093]: https://makingsense.atlassian.net/browse/DAT-2093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2093] - Create new endpoint get plan information given planId and type

Doppler.AccountPlans/Enums/BillingCreditTypeEnum.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
fix issue when calculate the amount for the chat plan
=> fix: fix issue when calculate the amount for the chat plan

Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromChatPlanHelper.cs
=> Fix issue with promocode

Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
Task: [DAT-2178](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2178)
[DAT-2178]: https://makingsense.atlassian.net/browse/DAT-2178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Filter non-active conversation plans

Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Fix issue calculate landing amount
=> [No-Task] - Fix issue calculate landing amount

Doppler.AccountPlans/Controllers/AccountPlansController.cs
fix issue for calculate landing amount
=> [no-task] fix issue for calculate landing amount

Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromChatPlanHelper.cs, Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromMarketingPlanHelper.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
fix issue when calculate next invoice date
=> [no-task] fix issue when calculate next invoice date

Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs
Add endpoint to get custom conversations plans
=> [no-task] Add endpoint to get custom conversations plans

Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
Task: [DAT-2223](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2223)
[DAT-2223]: https://makingsense.atlassian.net/browse/DAT-2223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2223] Order landing plans by fee

Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
Fix issue to calculate amount details
=> [no-task] - Fix issue to calculate amount details

Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Enums/PlanTypeEnum.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Model/OnSitePlanInformation.cs
Add endpoint to get the onsite plans
**Task:** [DAT-2244](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2244)
[DAT-2244]: https://makingsense.atlassian.net/browse/DAT-2244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2244] - Add endpoint to get the onsite plans

Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs
Add endpoint to get custom onsite plans
=> [DAT-2244]- Add endpoint to get custom onsite plans

Doppler.AccountPlans.Test/AuthorizationTest.cs, Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs, Doppler.AccountPlans.Test/GetCalculateUpgradeCostTestTest.cs, Doppler.AccountPlans.Test/GetPlanInformationTest.cs, Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Enums/AddOnType.cs, Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromMarketingPlanHelper.cs, Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromOnSitePlanHelper.cs, Doppler.AccountPlans/Helpers/ICalculateAmountDetalisHelper.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Model/AdditionalService.cs, Doppler.AccountPlans/Model/PlanInformation.cs, Doppler.AccountPlans/Model/UserPlan.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Update endpoint to calculate amount for the onsite plans
**Task:** [DAT-2249](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2249)
[DAT-2249]: https://makingsense.atlassian.net/browse/DAT-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2249] - Update endpoint to calculate amount for the onsite plans

Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromChatPlanHelper.cs, Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromOnSitePlanHelper.cs
Fix issue when calculate amount for the additional services
=> [No-Task] - Fix issue when calculate amount for the additional services

Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Enums/AddOnType.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Mappers/IAddOnMapper.cs, Doppler.AccountPlans/Mappers/OnSiteMapper.cs, Doppler.AccountPlans/Mappers/PushNotificationMapper.cs, Doppler.AccountPlans/Model/AddOnPlan.cs
Create endpoint to get addon plan details.
=> Create endpoint to get addon plan details

Doppler.AccountPlans/Controllers/AccountPlansController.cs, Doppler.AccountPlans/Enums/PlanTypeEnum.cs, Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromPushNotificationPlanHelper.cs, Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs, Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs, Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Calculate amount for the push notification plan
**Task:** [DAT-2427](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2427)
[DAT-2427]: https://makingsense.atlassian.net/browse/DAT-2427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2427] - Calculate amount for the push notification plan

Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromMarketingPlanHelper.cs
Fix issue when calculate the amount for the next month
=> [DAT-2508] - Fix issue when calculate the amount for the next month
